version: '2'
services:
  web:
    build: .
    image: too-mean
    links:
      - mongo
    volumes:
      - ./modules:/usr/src/app/modules/
    environment:
      - TOOMEAN_MONGO_HOST=mongo
      - VIRTUAL_HOST=dev.dcwright.xyz
      - VIRTUAL_PORT=3080
      - LETSENCRYPT_HOST=dev.dcwright.xyz
      - LETSENCRYPT_EMAIL=dylan@dcwright.xyz
      - TOOMEAN_APP_HOST=dev.dcwright.xyz
      - TOOMEAN_AWS_S3_DEST_URL=https://s3-us-west-2.amazonaws.com/wedding-uploads/
      - TOOMEAN_AWS_S3_BUCKET=wedding-uploads
      - TOOMEAN_UPLOADS_STRATEGY=s3
    env_file:
      - .env
  mongo:
    image: "mongo"
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - proxy
volumes:
  certs:
